name: Release

on:
    pull_request:
        types: closed
        branches:
            - master

jobs:
    release:
        name: Create release
        if: github.event.pull_request.merged
        runs-on: ubuntu-latest
        steps:
          - name: Set up workflow
            uses: actions/checkout@v2
          - name: Set up Node
            uses: actions/setup-node@v1
            with:
                node-version: 12
                registry-url: https://registry.npmjs.org/
          - name: Tag the library
            id: autotag
            uses: butlerlogic/action-autotag@stable
            with:
              GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
              tag_prefx: "v"
          - name: GitHub release
            uses: marvinpinto/action-automatic-releases@latest
            with:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              automatic_release_tag: ${{ steps.autotag.outputs.version }}
              prerelease: false

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
